controller_list:
  - name: fake_prismatic_controller
    type: $(arg fake_execution_type)
    joints:
      - extension_base_joint
  - name: fake_front_right_controller
    type: $(arg fake_execution_type)
    joints:
      - front_right_wheel_joint
  - name: fake_front_left_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_wheel_joint
  - name: fake_back_right_controller
    type: $(arg fake_execution_type)
    joints:
      - back_right_wheel_joint
  - name: fake_back_left_controller
    type: $(arg fake_execution_type)
    joints:
      - back_left_wheel_joint
initial:  # Define initial robot poses per group
#  - group: prismatic
#    pose: home

  []