controller_list:
  - name: prismatic_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - extension_base_joint
  - name: front_right_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - front_right_wheel_joint
  - name: front_left_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - front_left_wheel_joint
  - name: back_right_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_right_wheel_joint
  - name: back_left_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_left_wheel_joint
  - name: prismatic_controller_rename
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - extension_base_joint
  - name: front_right_controller_rename
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - front_right_wheel_joint
  - name: front_left_controller_rename
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - front_left_wheel_joint
  - name: back_right_controller_rename
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_right_wheel_joint
  - name: back_left_controller_rename
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_left_wheel_joint