<?xml version="1.0"?>

<robot name="hybrid_robotv0_2" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find hybrid_jumping_robot)/urdf/material.xacro"/>
    <xacro:include filename="$(find hybrid_jumping_robot)/urdf/plugins.gazebo.xacro"/>
    <xacro:include filename="$(find hybrid_jumping_robot)/urdf/macro.xacro"/>
    <xacro:include filename="$(find hybrid_jumping_robot)/urdf/transmission.xacro"/>

    <xacro:property name="wheel_r" value="0.075"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.025"/>
    <xacro:property name="base_length" value="0.25"/>
    <xacro:property name="base_width" value="0.15"/>
    <xacro:property name="base_height" value="0.04"/>
    <xacro:property name="base_mass" value="0.4"/>
    <xacro:property name="extension_length" value="0.20"/>
    <xacro:property name="extension_width" value="0.13"/>
    <xacro:property name="extension_height" value="0.03"/>
    <xacro:property name="extension_mass" value="0.4"/>
    <xacro:property name="motor_base_length" value="0.04"/>
    <xacro:property name="motor_base_width" value="${base_width}"/>
    <xacro:property name="motor_base_height" value="${base_height}"/>
    <xacro:property name="motor_base_mass" value="0.4"/>

    <link name="base">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertial mass="${base_mass}" length="${base_length}" width="${base_width}"
                            height="${base_height}"/>
    </link>

    <link name="motor_base">
        <visual>
            <geometry>
                <box size="${motor_base_length} ${motor_base_width}  ${motor_base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertial mass="${motor_base_mass}" length="${motor_base_length}" width="${motor_base_width}"
                            height="${motor_base_height}"/>
    </link>
    <joint name="base_motor_base_joint" type="fixed">
        <axis xyz="1 0 0"/>
        <parent link="base"/>
        <child link="motor_base"/>
        <origin xyz="${motor_base_length*0.5+base_length*0.5} 0 0"/>
    </joint>

    <link name="extension">
        <visual>
            <geometry>
                <box size="${extension_length} ${extension_width} ${extension_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${extension_length} ${extension_width} ${extension_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertial mass="${extension_mass}" length="${extension_length}" width="${extension_width}"
                            height="${extension_height}"/>
    </link>
    <joint name="extension_base_joint" type="prismatic">
        <axis xyz="1 0 0"/>
        <parent link="base"/>
        <child link="extension"/>
        <origin xyz="-0.1 0 0"/>
        <limit lower="-0.045" upper="0" effort="10000" velocity="1000"/>
        <joint_properties damping="1.0" friction="1.0"/>
    </joint>

    <xacro:wheel position="front" side="right" parent="motor_base" wheel_r="${wheel_r}" wheel_width="${wheel_width}"
                 base_length="${motor_base_length}" base_width="${base_width}" mass="${wheel_mass}"/>
    <xacro:wheel position="front" side="left" parent="motor_base" wheel_r="${wheel_r}" wheel_width="${wheel_width}"
                 base_length="${motor_base_length}" base_width="${base_width}" mass="${wheel_mass}"/>
    <xacro:wheel position="back" side="right" parent="extension" wheel_r="${wheel_r}" wheel_width="${wheel_width}"
                 base_length="${base_length}" base_width="${base_width}" mass="${wheel_mass}"/>
    <xacro:wheel position="back" side="left" parent="extension" wheel_r="${wheel_r}" wheel_width="${wheel_width}"
                 base_length="${base_length}" base_width="${base_width}" mass="${wheel_mass}"/>

</robot>
