<?xml version="1.0"?>
<robot name="hybrid_robotv0_2" xmlns:xacro="http://ros.org/wiki/xacro">


    <xacro:macro name="wheel" params="position side parent wheel_r wheel_width base_length base_width mass">

        <link name="${position}_${side}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:if value="${position == 'back'}">
                <xacro:cylinder_inertial mass="${0.025}" height="${wheel_width}" radii="${wheel_r}"/>
            </xacro:if>
            <xacro:if value="${position == 'front'}">
                <xacro:cylinder_inertial mass="${mass}" height="${wheel_width}" radii="${wheel_r}"/>
            </xacro:if>

        </link>

        <xacro:if value="${position == 'back'}">
            <joint name="${position}_${side}_wheel_joint" type="continuous">
                <xacro:property name="origin_x" value="${-(base_length/2-0.05)}"/>
                <xacro:property name="origin_y" value="${(base_width + wheel_width)/2}"/>
                <xacro:if value="${side == 'right'}">
                    <xacro:property name="origin_y" value="${-(base_width + wheel_width)/2}"/>
                </xacro:if>
                <axis xyz="0 0 1" rpy="0 0 0"/>
                <parent link="${parent}"/>
                <child link="${position}_${side}_wheel"/>
                <origin xyz="${origin_x} ${origin_y} 0" rpy="${pi/2} 0 0"/>
                <joint_properties damping="0.0" friction="0.0"/>
                <limit effort="0.0" velocity="100000.0"/>
            </joint>
        </xacro:if>
        <xacro:if value="${position == 'front'}">
            <joint name="${position}_${side}_wheel_joint" type="continuous">
                <xacro:property name="origin_x" value="${0}"/>
                <xacro:property name="origin_y" value="${(base_width + wheel_width)/2}"/>
                <xacro:if value="${side == 'right'}">
                    <xacro:property name="origin_y" value="${-(base_width + wheel_width)/2}"/>
                </xacro:if>
                <axis xyz="0 0 1" rpy="0 0 0"/>
                <parent link="${parent}"/>
                <child link="${position}_${side}_wheel"/>
                <origin xyz="${origin_x} ${origin_y} 0" rpy="${pi/2} 0 0"/>
                <limit effort="1000000" velocity="1000"/>
                <joint_properties damping="0.0" friction="10000.0"/>
            </joint>
        </xacro:if>

    </xacro:macro>
    <!--box_inertial makes it easier to implement mass and inertial for a box shape-->
    <xacro:macro name="box_inertial" params="mass length width height">
        <inertial>
            <mass value="${mass}"/>
            <inertia
                    ixx="${1/12*mass*(width*width+height*height)}"
                    ixy="0.0"
                    ixz="0.0"
                    iyy="${1/12*mass*(length*length+height*height)}"
                    iyz="0.0"
                    izz="${1/12*mass*(width*width+length*length)}"/>
        </inertial>
    </xacro:macro>
    <!--cylinder_inertial makes it easier to implement mass and inertial for a cylinder shape-->
    <xacro:macro name="cylinder_inertial" params="mass height radii">
        <inertial>
            <mass value="${mass}"/>
            <inertia
                    ixx="${1/12*mass*(3*radii*radii+height*height)}"
                    ixy="0.0"
                    ixz="0.0"
                    iyy="${1/12*mass*(3*radii*radii+height*height)}"
                    iyz="0.0"
                    izz="${0.5*mass*(radii*radii)}"/>
        </inertial>
    </xacro:macro>

</robot>
