hybrid_robot:
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01

  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - extension_base_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint
    sim_control_mode: 1  # 0: position, 1: velocity

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  controller_list:
    - name: prismatic_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        extension_base_joint
    - name: front_right_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        front_right_wheel_joint
    - name: front_left_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        front_left_wheel_joint
    - name: back_right_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        back_right_wheel_joint
    - name: back_left_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        back_left_wheel_joint

  # Position Controllers ---------------------------------------
  prismatic_controller:
    type: effort_controllers/JointPositionController
    joint: extension_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  front_right_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  front_left_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  back_right_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  back_left_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}