<?xml version="1.0"?>
<robot name="hybrid_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_r" value="0.15"/>
    <xacro:property name="wheel_width" value="0.02"/>
    <xacro:property name="base_length" value="1"/>
    <xacro:property name="base_width" value="0.5"/>
    <xacro:property name="base_height" value="0.1"/>
    <xacro:property name="extension_length" value="1"/>
    <xacro:property name="extension_width" value="0.45"/>
    <xacro:property name="extension_height" value="0.095"/>


    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <xacro:macro name="wheel" params="position side parent">

        <link name="${position}_${side}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_r}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1"/>
                <inertia ixx="0.005658333333333333" ixy="0" ixz="0" iyy="0.005658333333333333" iyz="0" izz="0.01125"/>
            </inertial>
        </link>
        <joint name="${position}_${side}_wheel_joint" type="continuous">
            <xacro:property name="origin_x" value="${base_length/2-0.05}"/>
            <xacro:if value="${position == 'back'}">
                <xacro:property name="origin_x" value="${-(base_length/2-0.05)}"/>
            </xacro:if>
            <xacro:property name="origin_y" value="${(base_width + wheel_width)/2}"/>
            <xacro:if value="${side == 'right'}">
                <xacro:property name="origin_y" value="${-(base_width + wheel_width)/2}"/>
            </xacro:if>
            <xacro:if value="${parent == 'extension'}">

            </xacro:if>
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="${position}_${side}_wheel"/>
            <origin xyz="${origin_x} ${origin_y} 0" rpy="${pi/2} 0 0"/>
        </joint>

    </xacro:macro>

    <link name="base">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="10"/>
            <inertia ixx="0.21666666666666667" ixy="0" ixz="0" iyy="0.8416666666666667" iyz="0" izz="1.0416666666666665"/>
        </inertial>
    </link>

    <link name="extension">
        <visual>
            <geometry>
                <box size="${extension_length} ${extension_width} ${extension_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${extension_length} ${extension_width} ${extension_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="10"/>
            <inertia ixx="0.17627083333333335" ixy="0" ixz="0" iyy="0.8408541666666667" iyz="0" izz="1.0020833333333334"/>
        </inertial>
    </link>
    <joint name="extension_base_joint" type="prismatic">
        <axis xyz="1 0 0"/>
        <parent link="base"/>
        <child link="extension"/>
        <origin xyz="-0.1 0 0"/>
        <limit lower="-0.9" upper="0" effort="100" velocity="10"/>
    </joint>

    <xacro:wheel position="front" side="right" parent="base"/>
    <xacro:wheel position="front" side="left" parent="base"/>
    <xacro:wheel position="back" side="right" parent="extension"/>
    <xacro:wheel position="back" side="left" parent="extension"/>

    <transmission name="trans_extension_base_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="extension_base_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="extension_base_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_front_right_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_right_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="front_right_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_front_left_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_left_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="front_left_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_back_right_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="back_right_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="back_right_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_back_left_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="back_left_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="back_left_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <gazebo>
        <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
            <robotNamespace>/hybrid_robot</robotNamespace>
        </plugin>
    </gazebo>
    <transmission name="trans_extension_base_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="extension_base_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="extension_base_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_front_right_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_right_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="front_right_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_front_left_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_left_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="front_left_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_back_right_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="back_right_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="back_right_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_back_left_wheel_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="back_left_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="back_left_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/hybrid_robot</robotNamespace>
        </plugin>
    </gazebo>

</robot>