# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - extension_base_joint
    - back_left_wheel_joint
    - back_right_wheel_joint
    - front_left_wheel_joint
    - front_right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: prismatic_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      extension_base_joint
  - name: front_right_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      front_right_wheel_joint
  - name: front_left_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      front_left_wheel_joint
  - name: back_right_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      back_right_wheel_joint
  - name: back_left_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      back_left_wheel_joint
prismatic_controller:
  type: effort_controllers/JointEffortController
  joints:
    extension_base_joint
  gains:
    extension_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
front_right_controller:
  type: effort_controllers/JointEffortController
  joints:
    front_right_wheel_joint
  gains:
    front_right_wheel_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
front_left_controller:
  type: effort_controllers/JointEffortController
  joints:
    front_left_wheel_joint
  gains:
    front_left_wheel_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
back_right_controller:
  type: effort_controllers/JointEffortController
  joints:
    back_right_wheel_joint
  gains:
    back_right_wheel_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
back_left_controller:
  type: effort_controllers/JointEffortController
  joints:
    back_left_wheel_joint
  gains:
    back_left_wheel_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1